name: AdvancedAntiCheat
version: 1.0
main: com.example.AdvancedAntiCheatPlugin
author: YourName
description: Simple anti-cheat plugin for Minecraft 1.8.8

permissions:
  anticheat.notify:
    description: Allows player to receive anticheat notifications.
    default: op
